repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
    -   id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    -   id: flake8